name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - xlrd
  - appmode
  - IPython
  - ipywidgets
  - seaborn
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
