name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - IPython.display
  - ipywidgets
  - seaborn
  - psutil
  - __future__
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
